PersonelUI/Controllers/DepartmanController.cs
using PersonelUI.Models.EntitiyFramework;
using PersonelUI.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PersonelUI.Controllers
{
    [Authorize(Roles = "A,U")]
    public class DepartmanController : Controller
    {
        PersonelDbEntities db = new PersonelDbEntities();


  
        public ActionResult Index()
        {
            var model = db.Departman.ToList();
            return View(model);
        }
        [HttpGet]
        public ActionResult DepartmanForm()
        {
            
            return View(new Departman());
        }

        [ValidateAntiForgeryToken]
        public ActionResult Kaydet(Departman departman)
        {
            if (!ModelState.IsValid) //geçerli değilse diyoruz
            {
                return View("DepartmanForm");
            }

            MesajViewModel model = new MesajViewModel(); //viewmeesaj'ı tanımladık

            if (departman.Id ==0)
            {

                db.Departman.Add(departman);
                model.Mesaj = departman.Ad + " Başarıyla Eklendi"; //mesaj için bu kodu ekledim
            }
            else
            {
                var guncellenecekDepartman = db.Departman.Find(departman.Id);
                if (guncellenecekDepartman==null)
                {
                    return HttpNotFound();
                }
                guncellenecekDepartman.Ad = departman.Ad;
                model.Mesaj = departman.Ad + " Başarıyla Güncellendi"; //mesaj için bu kodu ekledim
            }
            db.SaveChanges();
            //return RedirectToAction("index","departman");
            model.Status = true;
            model.LinkText = "Departman Listesi";
            model.Url = "/Departman";
            return View("_Mesaj",model); //modeli'ide gönderdik.
        }
        public ActionResult Guncelle(int id)
        {
            var model = db.Departman.Find(id); //id'i olanı bul
            if (model == null) //yani kişi elle sıfırlarsa.
                return HttpNotFound();
            return View("DepartmanForm",model);
        }
        public ActionResult Sil (int id)
        {
            var silinecekDb = db.Departman.Find(id);
            if (silinecekDb == null)
                return HttpNotFound();
            db.Departman.Remove(silinecekDb);
            db.SaveChanges();
            return RedirectToAction("index");
        }
    }
}

PersonelUI/Controllers/PersonelController.cs
using PersonelUI.Models.EntitiyFramework;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data.Entity;
using PersonelUI.ViewModels;

namespace PersonelUI.Controllers
{
    [Authorize(Roles = "A,U")]
    public class PersonelController : Controller
    {
        PersonelDbEntities db = new PersonelDbEntities();
        // GET: Personel
        public ActionResult Index()
        {
           var model= db.Personel.Include(x => x.Departman).ToList(); //join yapıyoruz.
            return View(model);
        }


        public ActionResult Yeni()
        {
            var model = new PersonelFormViewModel{
                Departmanlar = db.Departman.ToList(),
                Personel=new Personel()
            };
            return View("PersonelForm",model); //bu forma yönlendirdim.
        }
        [ValidateAntiForgeryToken]
        public ActionResult Kaydet(Personel personel)
        {
            if (!ModelState.IsValid)
            {
                var model = new PersonelFormViewModel()
                {
                    Departmanlar = db.Departman.ToList(),
                    Personel = personel
                };
                return RedirectToAction("PersonelForm",model);
            }
            if (personel.Id==0)
            {
                db.Personel.Add(personel);
            }
            else //güncelleme
            {
                db.Entry(personel).State = System.Data.Entity.EntityState.Modified; //bu kod tek satırda halletmemizi sağlıyor
            }
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult Guncelle (int id)
        {
            var model = new PersonelFormViewModel()
            {
                Departmanlar = db.Departman.ToList(),
                Personel = db.Personel.Find(id)
            };
            return View("PersonelForm", model);
        }
        public ActionResult Sil(int id)
        {
            var silinecekPersonel = db.Personel.Find(id);
            if (silinecekPersonel==null)
            {
                return HttpNotFound();
            }
                db.Personel.Remove(silinecekPersonel);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult PersonelleriListele(int id)
        {
            var model = db.Personel.Where(x => x.DepartmanId == id).ToList();
            return PartialView(model);
        }

        public int? ToplamMaas()
        {
            return db.Personel.Sum(x => x.Maas);
        }
        public ActionResult ToplamMaasAction()
        {
            ViewBag.Maas = db.Personel.Sum(x => x.Maas);
            return PartialView();
        }
    }
}

PersonelUI/Views/Departman/DepartmanForm.cshtml
@model PersonelUI.Models.EntitiyFramework.Departman
@{
    ViewBag.Title = "Yeni";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Yeni Departman Ekle</h2>



@*<form method="post">
        <div class="form-group">
            <label>Departman Adı</label>
            <input type="text" name="Ad" class="form-control" />
        </div>
        <button type="submit" class="btn btn-success">Ekle</button>
    </form>*@
@*@using (Html.BeginForm("Kaydet", "Departman", FormMethod.Post)) bunu ajaxbegin form ile yapuyoruz*@
<div id="mesaj"></div>
@using (Ajax.BeginForm("Kaydet", "Departman",new AjaxOptions { HttpMethod="POST", UpdateTargetId="mesaj" })) //form oluşturduk
{
    @Html.ValidationSummary()
    @Html.AntiForgeryToken()
    <div class="form-group">

        @Html.LabelFor(m => m.Ad) @*sen bana bir model oluştur modeldeki ada göre oluştur*@
        @Html.TextBoxFor(m => m.Ad, new { @class = "form-control" }) @* ada göre Ad oluşturdu. *@
        @Html.ValidationMessageFor(m => m.Ad)
        @Html.HiddenFor(m => m.Id)

    </div>
    <button type="submit" class="btn btn-success">Kaydet</button>
}

@section scripts
{
    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>


}

PersonelUI/Views/Departman/Index.cshtml
@using PersonelUI.Models.EntitiyFramework;
@model List<Departman>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<h2>Departmanlar Listesi</h2>
<a class="btn btn-success" href="/Departman/Departmanform">Yeni Departman</a>
<table class="table table-bordered" id="tblDepartmanlar">
    <thead>
        <tr>
            <td>Id</td>
            <td>Ad</td>
            <td>Güncelle</td>
            <td>Sil</td>
            <td>Sil 2 Ajax</td>
            <th>Personeller</th>
            <th>Personeller Ajax ile</th>
        </tr>
    </thead>
    <thead>
        @foreach (var d in Model)
        {
        <tr>
            <td>@d.Id</td>
            <td>@d.Ad</td>
            <td><a class="btn btn-primary" href="/Departman/Guncelle/@d.Id">Güncelle</a></td>
            <td><a class="btn btn-danger" href="/Departman/Sil/@d.Id">Sil</a></td>
            <td><a class="btn btn-danger btnDepartmanSil" data-id="@d.Id">Sil2</a></td>
            <td>@Html.ActionLink("Personelleri Göster","PersonelleriListele","Personel", new {id=d.Id },new {@class="btn btn-primary" })</td>
            <td>@Ajax.ActionLink("Personelleri Göster","PersonelleriListele","Personel", new { id=d.Id }, new AjaxOptions {HttpMethod="GET", UpdateTargetId= "personelListesi" }, new {@class="btn btn-primary" })</td>
        </tr>
        }

    </thead>
</table>
<div id="personelListesi">

</div>